name: CI - Test & Push (testing)

on:
  push:
    branches: [ "testing" ]

permissions:
  contents: read
  packages: write

env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME:     ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD:     ${{ secrets.ACR_PASSWORD }}
  IMAGE_TAG:        ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Frontend tests if Node project present ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run frontend tests (if present)
        shell: bash
        run: |
          set -e
          ROOT="."
          [ -d "./task10_2d" ] && ROOT="./task10_2d"
          if [ -f "$ROOT/frontend/package.json" ]; then
            cd "$ROOT/frontend"
            npm ci
            npm test --if-present
          else
            echo "No frontend package.json; skipping frontend tests."
          fi

      # --- Backend tests if Python present ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run backend tests (if present)
        shell: bash
        run: |
          set -e
          ROOT="."
          [ -d "./task10_2d" ] && ROOT="./task10_2d"
          for svc in customer_service order_service product_service; do
            SVC_DIR="$ROOT/backend/$svc"
            if [ -d "$SVC_DIR" ]; then
              if [ -f "$SVC_DIR/requirements.txt" ]; then
                python -m pip install -U pip
                pip install -r "$SVC_DIR/requirements.txt" || true
              fi
              if ls "$SVC_DIR" | grep -qiE '^tests?$'; then
                pytest -q "$SVC_DIR" || true
              else
                echo "No tests in $SVC_DIR; skipping."
              fi
            fi
          done

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show repo tree (debug)
        shell: bash
        run: |
          pwd
          git rev-parse --abbrev-ref HEAD
          ls -la
          find . -maxdepth 3 -type d | sort

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}

      - name: Build & push images (auto-detect root or task10_2d)
        shell: bash
        run: |
          set -euo pipefail
          ROOT="."
          [ -d "./task10_2d" ] && ROOT="./task10_2d"
          echo "Using ROOT=$ROOT"

          # services we expect; we’ll skip any that don’t exist
          declare -a services=("frontend" "backend/customer_service" "backend/order_service" "backend/product_service")

          for svc in "${services[@]}"; do
            ctx="$ROOT/$svc"
            df="$ctx/Dockerfile"
            name="${svc##*/}"          # repo name (frontend, customer_service, etc.)

            if [ -d "$ctx" ] && [ -f "$df" ]; then
              echo "==> Building $name from $ctx"
              docker buildx build \
                --file "$df" \
                --tag  "${ACR_LOGIN_SERVER}/${name}:${IMAGE_TAG}" \
                --tag  "${ACR_LOGIN_SERVER}/${name}:latest" \
                --push "$ctx"
            else
              echo "SKIP: $svc not found (ctx=$ctx, df=$df)."
            fi
          done
